### ISSUE TITLE
Datasets of climate zone 1-4 missing  files carbbon_intensity.csv

### ISSUE THREAD

**Issue by BudingZ** [intelligent-environments-lab/CityLearn#12]
The datasets in Climate_zone 1-4 miss files about carbbon_intensity.csv; thus, the env can't be initialized by Climate_zone 1-4.  And it said in the paper "MARLISA: Multi-Agent Reinforcement Learning with Iterative Sequential Action Selection for Load Shaping of Grid-Interactive Connected Buildings" that the datasets in climate zone 2A contain five years datasets. But in fact, there are no datasets of climate zone containing more than five years in this project. I am confused about the datasets used in papers. I would be appreciated if you can upload a dataset explanation document and missing files carbbon_intensity.csv.
![微信截图_20211227164021](https://user-images.githubusercontent.com/48684338/147453035-2f696b1d-91a6-4e51-ad02-0552c82b8b01.png)

**Comment by kingsleynweye** [comment]
That must be a typo in the paper referring to CZ2 as the CZ having the 5 years dataset. [CZ5](https://github.com/intelligent-environments-lab/CityLearn/tree/master/data/Climate_Zone_5) has the 5 years datasets.

You can use the [carbon_intensity.csv](https://raw.githubusercontent.com/intelligent-environments-lab/CityLearn/master/data/Climate_Zone_5/carbon_intensity.csv) in CZ5 folder to get day-of-year average emission values. This will give you 8760 hours worth of data to use in simulation in other CZ1-4 that have 1 year of weather and building energy simulation data.

**Comment by BudingZ** [comment]
CZ5 has the 4 years datasets, 8760*4=35040.  It seems like that CZ5 losses one year datasets. Thanks for your reply.
![微信截图_20211228160219](https://user-images.githubusercontent.com/48684338/147543454-fe108dcc-cea8-4e02-85df-d6632b064502.png)
![微信截图_20211228160232](https://user-images.githubusercontent.com/48684338/147543458-850b650e-39e7-4552-bdeb-2da92a889832.png)
