### ISSUE TITLE
Battery.energy_balance() applies efficiency losses twice

### ISSUE THREAD

**Issue by ludwigbald** [intelligent-environments-lab/CityLearn#24]
Battery.energy_balance() starts with a call to super().energy_balance().

In both calls, efficiency penalties are applied to the energy balance, so they are applied twice. I think that is wrong, but it should be an easy fix in the Battery module.

**Comment by nagyzoltan** [comment]
Thanks @ludwigbald ! We’ll take a look.

**Comment by kingsleynweye** [comment]
Thanks @ludwigbald thanks for catching this. It's been fixed in a recent merge but has not been published as a release yet. Will notify when that is done and close out the issue then.

**Comment by kingsleynweye** [comment]
New release is here with the fix implemented @ludwigbald https://github.com/intelligent-environments-lab/CityLearn/releases/tag/v1.3.5.

I will close out this issue.
