### ISSUE TITLE
Dimension error within the environment

### ISSUE THREAD

**Issue by nicosquare** [intelligent-environments-lab/CityLearn#26]
Hi everyone,

I was doing some experimentation and I think I faced an issue that is outside of my control. When getting the reward from `env.step` method I'm getting this error:

```
ValueError: operands could not be broadcast together with shapes (8760,) (8761,) 
```

It was raised when trying to compute the net_electricity_consumption function (the original) in the building.py line 344. 

Could anyone give me a hint about how to solve this issue?

Thanks in advance!

**Comment by kingsleynweye** [comment]
Hi @nicosquare  please, can you confirm what version of citylearn you are using?

**Comment by nicosquare** [comment]
Hi @kingsleynweye!

I'm using version 1.3.4.

**Comment by kingsleynweye** [comment]
@nicosquare checking if you were able to resolve this eventually?

**Comment by kingsleynweye** [comment]
Closing out this issue @nicosquare as it seems to be resolved but also, the CityLearn Challenge 2022 is now completed. Please, open a new issue if you still have related problems.
