### ISSUE TITLE
Error while running citylearn_sb3.py

### ISSUE THREAD

**Issue by anujshah1003** [intelligent-environments-lab/CityLearn#28]
on running the line 
env = ss.pettingzoo_env_to_vec_env_v1(citylearn_pettingzoo_env)

I get the error as 
AssertionError: observation spaces not consistent. Perhaps you should wrap with `supersuit.aec_wrappers.pad_observations`?

when i change to 
env = ss.pad_observations_v0(citylearn_pettingzoo_env)

creating env does not throws any error

but on calling the model, it throws error as 

File "C:\Users\anuj\Anaconda3\envs\city_challenge\lib\site-packages\stable_baselines3\common\vec_env\util.py", line 74, in obs_space_info
    shapes[key] = box.shape

AttributeError: 'function' object has no attribute 'shape'

Anyone knows how we can train models from sb3 for citylearn

**Comment by kingsleynweye** [comment]
@anujshah1003 Please refer to [this previous issue](https://github.com/intelligent-environments-lab/CityLearn/issues/21) fo questions concerning `citylearn_sb3.py`.
