### ISSUE TITLE
Question regarding evaluation

### ISSUE THREAD

**Issue by TheoZan** [intelligent-environments-lab/CityLearn#36]
Hello, thanks for providing this environment.

I took part in the 2022 challenge and I am looking at the 2021 environment. I'm confused on the right way to evaluate the agent. In the 2022 challenge we have the env.evaluate() function, in the 2021 environment it seems that the env.cost() method is used to evaluate the agent (from the challenge page), but it doen't seem to exist anymore.

Do we have to use the cost functions in the citylearn.cost_function file and implement our own cost function ?

Thank you !

**Comment by kingsleynweye** [comment]
@TheoZan, the environment that was used in the CityLearn Challenge 2021 is different from what was used in the CityLearn Challenge 2022.  

The CityLearn Challenge 2021 has been archived and can be downloaded here: [https://github.com/intelligent-environments-lab/CityLearn/releases/tag/v1.0.0](https://github.com/intelligent-environments-lab/CityLearn/releases/tag/v1.0.0). In this release, you will find the `env.cost()` function.

If you want to use the same cost function from CityLearn Challenge 2021 in the CityLearn Challenge 2022 environment, they are available in the `citylearn.cost_function` module and you can calculate by calling the relevant function.

**Comment by kingsleynweye** [comment]
I am closing out this issue @TheoZan since there has been no response. Please, let me know to reopen if needed.
