### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by kingsleynweye** [intelligent-environments-lab/CityLearn#39]
As a CityLearn developer, I want to know when a functionality in CityLearn fails after a change has been made to the source code or its dependencies' versions so that I can easily debug the problem and release a new CityLearn version.

## Acceptance Criteria
- [ ] Tests for all methods in the [CityLearn Python package](https://github.com/intelligent-environments-lab/CityLearn/tree/master/citylearn).
- [ ] Workflow in the [workflow directory](https://github.com/intelligent-environments-lab/CityLearn/tree/master/.github/workflows) that runs tests each time a push is made to the master branch and returns an output that can be checked on to see failing tests.

## References
1. [Getting Started With Testing in Python](https://realpython.com/python-testing/).

**Comment by Xtian-hub** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_14944\1249709747.py](https://file+.vscode-resource.vscode-cdn.net/g%3A/%E5%AD%98%E7%9B%98/%E7%A0%94%E7%A9%B6%E7%94%9F/%E9%A1%B9%E7%9B%AE/%E8%AE%BA%E6%96%87%E5%AE%9E%E9%AA%8C/citylearn/~/AppData/Local/Temp/ipykernel_14944/1249709747.py) in 
      8 env = StableBaselines3Wrapper(env)
      9 model = SAC('MlpPolicy', env)
---> 10 model.learn(total_timesteps=env.time_steps*2)
     11 
     12 # evaluate
...
ValueError: not enough values to unpack (expected 2, got 1)
I ran quickstart.ipynb without making any changes and it throws this error, may I ask why?

**Comment by kingsleynweye** [comment]
Hi @Xtian-hub, please can you open a new issue for this?

**Comment by Xtian-hub** [comment]
> 嗨，请您为此打开一个新问题吗？

SURE,keep following

**Comment by Xtian-hub** [comment]
I've submitted a new issue.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kingsley ***@***.***&gt;; 
发送时间: 2023年7月24日(星期一) 晚上9:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [intelligent-environments-lab/CityLearn] Testing (Issue #39)





 
Closed #39 as completed.
