### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by mas21bd** [intelligent-environments-lab/CityLearn#45]
I have an error when I run example module for RBC and SAC showing AttributeError: type object 'CostFunction' has no attribute 'net_electricity_consumption'

When I run quickstart example it's run fine without any error.

Thank you

**Comment by kingsleynweye** [comment]
@mas21bd  thanks for the observation. The example.ipynb is deprecated and is replaced with the quickstart.ipynb. I have deleted the example.ipynb notebook now.

**Comment by mas21bd** [comment]
Thanks for the quick response.
