### ISSUE TITLE
Where can we find a winner solution for CityLearn Challenge 2022

### ISSUE THREAD

**Issue by Skywuuuu** [intelligent-environments-lab/CityLearn#53]
Hi,

I tried to find the solution on this [website](https://www.aicrowd.com/challenges/neurips-2022-citylearn-challenge/leaderboards?challenge_leaderboard_extra_id=1237&challenge_round_id=1253). However, when I clicked view of the leaderboard winner and then clicked the REPO_URL has expired and I couldn't find any solution. 

Where can we find a winner solution for CityLearn Challenge 2022 or solution for previous challenges? Or is there a competition solution paper available?

Thank you!!

**Comment by nagyzoltan** [comment]
Hi @Skywuuuu, we're about the release them publicly. Check back in a week tops. The solutions paper is currently under review it should come out soon.

the 2022 challenge winners have published their solution here: https://ieeexplore.ieee.org/abstract/document/10090669
you can also watch their solution in their NeurIPS22 presentation
the 2021 challenge winner has published their solution here : **https://arxiv.org/abs/2212.01939**

hope this helps.

**Comment by Skywuuuu** [comment]
@nagyzoltan It helps a lot! Thank you!

**Comment by nagyzoltan** [comment]
@Skywuuuu the top 3 solutions should be public now on the AICrowd website.
