### ISSUE TITLE
[FEATURE REQUEST] Is there a way to access the planned states and actions? 

### ISSUE THREAD

**Issue by lijiayi9712** [intelligent-environments-lab/CityLearn#57]
**Is your feature request related to a problem? Please describe.**
I am trying to test a pricing algorithm using CityLearn platform. I am wondering if there are ways to access the planned states and actions of each building, or whether the environment has planned states and actions? 

**Describe the solution you'd like**

**Describe alternatives you've considered**
I have considered randomly initializing random planned states for each building if the environment doesn't have one already. 

**Additional context**
Thank you!

**Comment by kingsleynweye** [comment]
@lijiayi9712 you can access active building [observations](https://www.citylearn.net/api/citylearn.building.html#citylearn.building.Building.active_observations) and [actions](https://www.citylearn.net/api/citylearn.building.html#citylearn.building.Building.active_actions) to tell you the names of observations and actions that will be in use during the simulation.

To get a building's observation values for the current time step, use the [observations](https://www.citylearn.net/api/citylearn.building.html#citylearn.building.Building.observations) method. There is a similar [observations property](https://www.citylearn.net/api/citylearn.citylearn.html#citylearn.citylearn.CityLearnEnv.observations) at the `env` level.

The actions for the current time step are those parsed to the [step](https://www.citylearn.net/api/citylearn.citylearn.html#citylearn.citylearn.CityLearnEnv.step) function.

Please, let me know if these answer your questions.

**Comment by lijiayi9712** [comment]
Thanks!
