### ISSUE TITLE
Upload weight file in submission?

### ISSUE THREAD

**Issue by QasimWani** [intelligent-environments-lab/CityLearn#6]
In last years competition, we were allowed to submit an optional file for model weight and policy params. There was no information on the same for this years' competition. Can we submit a pre-trained agent, i.e. include the weight file?

**Comment by nagyzoltan** [comment]
We have changed slightly the format and rules for this year. Please see rule #4 "The submission of pre-trained RL agents is not allowed". The agents will be also evaluated on how quickly they learn and not only how good the final policy is. Does this help?

**Comment by nicosquare** [comment]
Hi!

Does this still apply to the current version of the competition? I was looking at the rules for this version and could find anything related.

Thanks!

**Comment by nagyzoltan** [comment]
hi @nicosquare ,

no, the comment above was for the 2021 edition, it doesn’t apply to 2022.
