### ISSUE TITLE
[BUG] citylearn.reward_function.MARL

### ISSUE THREAD

**Issue by Skywuuuu** [intelligent-environments-lab/CityLearn#60]
Hi, I think there is a bug in ```citylearn.reward_function.MARL```.

## Issue Description

Please provide a brief description of the issue.
When I use _MARL_ reward function in file ```citylearn.reward_function``` as my reward function, bug appears at line 64 of this file. 

## Expected Behavior

It should give the maximum number between _0_ and _district_electricity_consumption_.

## Actual Behavior

TypeError: 'numpy.float64' object cannot be interpreted as an integer

## Steps to Reproduce

Just replace the reward function to MARL, and then the bug appears.

## Environment

- CityLearn version: 1.8.0
- Operating System: Ubuntu 22.04
- Python version: 3.8.0

## Possible Solution

Simply add parentheses inside the ```np.nanmax```.
```python
reward = np.sign(building_electricity_consumption)*0.01*building_electricity_consumption**2*np.nanmax((0, district_electricity_consumption))
```

**Comment by kingsleynweye** [comment]
Hi @Skywuuuu thanks for finding the bug and proposing the solution. I just pushed a commit that fixes it. You will need to update your CityLearn version to the most recent release to have the fix as well as other updates:

```console
pip install CityLearn==2.0b3
```
