### ISSUE TITLE
Why is max_heating defined in terms of cop_cooling and not cop_heating?

### ISSUE THREAD

**Issue by QasimWani** [intelligent-environments-lab/CityLearn#7]
https://github.com/intelligent-environments-lab/CityLearn/blob/8245a5447acb504f73a6da7d62f5b5ec35fcb1cf/energy_models.py#L373

`max_cooling` is defined as `min(max_electric_power, self.nominal_power)*self.cop_cooling[self.time_step]`. But `max_heating` is defined as same. Is it supposed to be `cop_heating`?

**Comment by nagyzoltan** [comment]
This is indeed a bug that we will fix in the next release. However, since the current setup is in a cooling dominated climate, it should not impact your results significantly. Sorry for the getting back to you this late!
