### ISSUE TITLE
compatitable issue 

### ISSUE THREAD

**Issue by SHITIANYU-hue** [intelligent-environments-lab/CityLearn#87]
when i run : 

i created a python=3.11 environment, and i run : 

pip install CityLearn

it will have the following issue:

<img width="1294" alt="image" src="https://github.com/intelligent-environments-lab/CityLearn/assets/38762389/90ac3908-77fb-437f-97db-43fc7482317a">

<img width="1504" alt="image" src="https://github.com/intelligent-environments-lab/CityLearn/assets/38762389/98de8acf-69d7-469e-a9e6-342e2c40b82f">

**Comment by kingsleynweye** [comment]
@SHITIANYU-hue  CityLearn is best used with Python 3.7 for now. Will update the code to use later Python versions in the near future.

**Comment by SHITIANYU-hue** [comment]
Hi @kingsleynweye.  Thanks for your reply! 

I found another compatible issue when i run : python local_evaluation.py , i think it is related to the environment
https://gitlab.aicrowd.com/aicrowd/challenges/citylearn-challenge/citylearn-2023-starter-kit/-/blob/master/local_evaluation.py 

<img width="1300" alt="image" src="https://github.com/intelligent-environments-lab/CityLearn/assets/38762389/71c61f69-aec5-4f6e-85e7-47542180c538">

**Comment by kingsleynweye** [comment]
> Hi @kingsleynweye.  Thanks for your reply! 
> 
> 
> 
> I found another compatible issue when i run : python local_evaluation.py , i think it is related to the environment
> 
> https://gitlab.aicrowd.com/aicrowd/challenges/citylearn-challenge/citylearn-2023-starter-kit/-/blob/master/local_evaluation.py 
> 
> 
> 
> <img width="1300" alt="image" src="https://github.com/intelligent-environments-lab/CityLearn/assets/38762389/71c61f69-aec5-4f6e-85e7-47542180c538">
> 
> 

This is most likely a CityLearn environment version issue as power outage simulation was only recently added. Update your version to CityLearn==2.1b9 to fix it as it is the correct version for Phase 2 of the 2023 Challenge.
