### ISSUE TITLE
Question: Mapping discrete actions to continuous space

### ISSUE THREAD

**Issue by KandBM** [intelligent-environments-lab/CityLearn#98]
I've trained a PPO using 20 discrete actions (controlling electrical SOC) and I'm trying to explain what each action does, is there a way to map them back to the continuous space from [-1.0, 1.0]? I'm assuming 0 is a full charge and equivalent to 1.0, and 19 to -1.0, but how could I map out the intermediate values?

Thanks!

**Comment by kingsleynweye** [comment]
@KandBM, you can either create your own custom wrapper that helps you with the mapping. The idea behind wrappers in explained in the [Gym docs](https://www.gymlibrary.dev/api/wrappers/). or 

Alternatively, you may be able to use the in-built [DiscreteObservationWrapper](https://www.citylearn.net/api/citylearn.wrappers.html#citylearn.wrappers.DiscreteObservationWrapper) and [DiscreteActionWrapper](https://www.citylearn.net/api/citylearn.wrappers.html#citylearn.wrappers.DiscreteActionWrapper) wrappers. You can also use the [DiscreteSpaceWrapper](https://www.citylearn.net/api/citylearn.wrappers.html#citylearn.wrappers.DiscreteSpaceWrapper) wrapper that combines the two. These wrappers were written for the purpose of being able to use a Tabular Q-Learning agent in the environment but might work for your PPO implementation. If you want to see an example of how they are used, see the `An Introduction to Tabular Q-Learning Algorithm as an Adaptive Controller` section of the [tutorial notebook](https://github.com/intelligent-environments-lab/CityLearn/blob/master/examples/tutorial.ipynb).

Some things to note when using our current implementation of discretizing spaces:
- It has only been tested against a single-value observation and action space with a very small number of bins. Larger observation and action spaces as well as bins can lead to memory issues when initializing the wrappers, building and updating the Q-Table. For your PPO example, this might not been an issue if you implement your own discretization wrapper or if the PPO algorithm handles the Q-Table more efficiently than we have.
- We have not validated our datasets with discretized spaces thus, it is more likely than not that there are bugs in our existing discretization source code. If you choose to use our implementation for discretization and find any bugs please, feel free to make a pull-request that fixes the bugs as we do not plan to maintain neither the Tabular Q-Learning nor discretization source code ourselves at the moment.
